package gui;

import javax.swing.*;

public class HomeUtente {

    private JPanel HomeUtente;
    private JTabbedPane TabbedPane;
    private JPanel Catalogo;
    private JPanel Profilo;
    private JPanel Libreria;
    private JTextField RicercaLibreria;
    private JList ListaLibreria;
    private JToolBar ToolBarLibreria;
    private JLabel EdizioneLibreria;
    private JLabel PiattaformaDiGiocoLibreria;
    private JLabel DataRilascioLibreria;
    private JLabel PrezzoAcquistoLibreria;
    private JLabel CategoriaLibreria;
    private JLabel PegiLibreria;
    private JLabel KeyLibreria;
    private JLabel DataAcquistoLibreria;
    private JButton PulsanteFiltra;
    private JButton PulsanteResetFiltri;
    private JComboBox CategorieFiltro;
    private JButton DataFiltro;
    private JButton PrezzoAcquistoFiltro;
    private JComboBox CategoriaFiltro;
    private JComboBox PegiFiltro;
    private JButton DataAcquistoFiltro;
    private JButton PulsanteRecensione;
    private JButton PulsanteCopiaKey;
    private JScrollPane ScrollPaneLibreria;
    private JButton PulsanteAggiungiSaldo;
    private JButton PulsanteModificaInformazioni;
    private JList ListaAmiciUtente;
    private JTextField RicercaAmici;
    private JCheckBox CheckBoxAmici;
    private JButton PulsanteVisualizzaRecensioni;
    private JList ListaSviluppatori;
    private JTextField RicercaSviluppatori;
    private JCheckBox CheckBoxSeguiti;
    private JButton PulsanteSegui;
    private JButton PulsanteAggiungiAmico;
    private JLabel DataCreazioneAccount;
    private JLabel TestoBannato;
    private JLabel TestoNome;
    private JLabel TestoGenere;
    private JLabel TestoEmail;
    private JLabel TestoDataDiNascita;
    private JLabel TestoNumeroGiochiAcquistati;
    private JLabel TestoNumeroRecensioniRilasciate;
    private JLabel TestoSaldo;
    private JScrollPane ScrollPaneListaAmici;
    private JScrollPane ScrollPaneListaSviluppatori;
    private JLabel TestoGiochiRilasciati;
    private JLabel TestoGiocoPiuVenduto;
    private JLabel TestoGiochiAcquistatiAmico;
    private JLabel TestoNumeroRecensioniAmico;
    private JLabel TestoGenereAmico;
    private JLabel TestoBannatoAmico;
    private JToolBar ToolBarSviluppatore;
    private JToolBar ToolBarAmico;
    private JLabel TestoProfilo;
    private JLabel TestoCommunity;
    private JPanel Carrello;
    private JList ListaCatalogo;
    private JButton PulsanteAcquista;
    private JComboBox PiattaformaFiltroCatalogo;
    private JSlider SliderPrezzoCatalogo;
    private JComboBox GenereFiltroCatalogo;
    private JComboBox PegiFiltroCatalogo;
    private JButton PulsanteDataDiRilascioFiltroCatalogo;
    private JComboBox CategoriaFiltroCatalogo;
    private JCheckBox CheckBoxInPromozione;
    private JCheckBox CheckBoXSviluppatori;
    private JList ListaRecensioniCatalogo;
    private JTextField RicercaCatalogo;
    private JLabel PegiCatalogo;
    private JLabel GenereCatalogo;
    private JLabel PiattaformaCatalogo;
    private JLabel PrezzoCatalogo;
    private JLabel CategoriaCatalogo;
    private JTextArea DescrizioneRecensioneCatalogo;
    private JButton PulsanteDislike;
    private JButton PulsanteLike;
    private JLabel DescrizioneCatalogo;
    private JLabel VotoCatalogo;
    private JLabel RecensioniCatalogo;
    private JToolBar ToolBarCatalogo;
    private JLabel PrezzoFiltroCatalogo;
    private JLabel DataDiRilascioCatalogo;
    private JLabel SviluppatoreCatalogo;
    private JLabel ValutazioneRecensioneCatalogo;
    private JLabel GeneriLibreria;
    private JLabel SviluppatoreLibreria;
    private JTextArea DescrizioneSviluppaotreProfilo;
    private JButton PulsanteRimuoviAmico;
    private JButton PulsanteLogout;

    public static void main(String[] args) {
        JFrame frame = new JFrame("HomeUtente");
        frame.setContentPane(new HomeUtente().HomeUtente);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

}
